version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    command: ["flask", "run", "-h", "0.0.0.0"]