version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 5000:5000
    env_file:
      - .env
    command: ["flask", "run", "-h", "0.0.0.0"]